## Ejercicio 6
Factorice las siguientes matrices en la descomposición LU mediante el algoritmo de factorización LU con l_ii = 1 para todas las i.

In [11]:
import numpy as np
import logging

def descomposicion_LU(A: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Realiza la descomposición LU de una matriz cuadrada A.
    [IMPORTANTE] No se realiza pivoteo.

    ## Parameters

    ``A``: matriz cuadrada de tamaño n-by-n.

    ## Return

    ``L``: matriz triangular inferior.

    ``U``: matriz triangular superior. Se obtiene de la matriz ``A`` después de aplicar la eliminación gaussiana.
    """
    A = np.array(A, dtype=float)  # Convertir a float para evitar problemas con enteros

    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."
    n = A.shape[0]

    L = np.zeros((n, n), dtype=float)

    for i in range(0, n):  # Loop por columna

        # --- Determinar pivote
        if abs(A[i, i]) < 1e-12:  # Comparar con un valor pequeño en lugar de cero directamente
            raise ValueError("No existe solución única debido a un pivote cero.")

        # --- Eliminación: loop por fila
        L[i, i] = 1
        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]
            L[j, i] = m

        logging.info(f"\n{A}")

    if abs(A[n - 1, n - 1]) < 1e-12:  # Verificar nuevamente el último elemento diagonal
        raise ValueError("No existe solución única debido a un pivote cero.")

    U = A  # Renombrar A a U para mayor claridad

    return L, U


## Literal a

In [12]:
import numpy as np

A = np.array([
    [2, -1, 1],
    [3, 3, 9],
    [3, 3, 5]
])

L, U = descomposicion_LU(A)
print("Matriz L\n", L, "\n")
print("Matriz U\n",U)

Matriz L
 [[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]] 

Matriz U
 [[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]


## Literal b

In [13]:
import numpy as np

B = np.array([
    [1.012, -2.132, 3.104],
    [-2.132, 4.096, -7.013],
    [3.104, -7.013, 0.014]
])

L, U = descomposicion_LU(B)
print("Matriz L\n",L, "\n")
print("Matriz L\n",U)

Matriz L
 [[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]] 

Matriz L
 [[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]


## Literal c

In [15]:
import numpy as np

C = np.array([
    [2, 0, 0, 0],
    [1, 1.5, 0, 0],
    [0, -3, 0.5, 0],
    [2, -2, 1, 1]
])

L, U = descomposicion_LU(C)
print("Matriz L\n",L, "\n")
print("Matriz U\n",U)

Matriz L
 [[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -2.          1.          0.        ]
 [ 1.         -1.33333333  2.          1.        ]] 

Matriz U
 [[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]


In [16]:
import numpy as np

D = np.array([
    [2.1756, 4.0231, -2.1732, 5.1967],
    [-4.0231, 6, 0, 1.1973], 
    [-1, -5.2107, 1.1111, 0],
    [6.0235, 7, 0, -4.1561]
])

L, U = descomposicion_LU(D)
print("Matriz L\n",L, "\n")
print("Matriz U\n",U)

Matriz L
 [[ 1.          0.          0.          0.        ]
 [-1.84919103  1.          0.          0.        ]
 [-0.45964332 -0.25012194  1.          0.        ]
 [ 2.76866152 -0.30794361 -5.35228302  1.        ]] 

Matriz U
 [[ 2.17560000e+00  4.02310000e+00 -2.17320000e+00  5.19670000e+00]
 [ 0.00000000e+00  1.34394804e+01 -4.01866194e+00  1.08069910e+01]
 [ 0.00000000e+00  4.44089210e-16 -8.92952394e-01  5.09169403e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.20361280e+01]]


## Ejercicio 7
7. Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema
lineal usando la descomposición LU y, a continuación, resuelva los siguientes sistemas lineales.

In [3]:
import numpy as np
def eliminacion_gaussiana(A: np.ndarray) -> np.ndarray:
    if not isinstance(A, np.ndarray):
        A = np.array(A)
    assert A.shape[0] == A.shape[1] - 1, "La matriz A debe ser de tamanio n-by-(n+1)."
    n = A.shape[0]

    for i in range(0, n - 1):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solucion unica.")
        
        if p != i:
            # swap rows
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]


    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solucion unica.")

        print(f"\n{A}")
    solucion = np.zeros(n)
    solucion[n - 1] = A[n - 1, n] / A[n - 1, n - 1]

    for i in range(n - 2, -1, -1):
        suma = 0
        for j in range(i + 1, n):
            suma += A[i, j] * solucion[j]
        solucion[i] = (A[i, n] - suma) / A[i, i]

    return solucion

## Literal a

In [4]:
A = [
    [2, -1, 1, -1],
    [3, 3, 9, 0], 
    [3, 3, 5, 4]
]

sol = eliminacion_gaussiana(A)
print(sol)

[ 1.  2. -1.]


## Literal b

In [5]:

B = [
    [1.012, -2.132, 3.104, 1.984],
    [-2.132, 4.096, -7.013, -5.049], 
    [3.104, -7.013, 0.014, -3.895]
]

sol = eliminacion_gaussiana(B)
print(sol)

[1. 1. 1.]


## Literal C

In [7]:
C = [
    [2, 0, 0, 0, 3],
    [1, 1.5, 0, 0, 4.5], 
    [0, -3, 0.5, 0, -6.6],
    [2, -2, 1, 1, 0.8]
]

sol = eliminacion_gaussiana(C)
print(sol)

[ 1.5  2.  -1.2  3. ]


## Literal D

In [8]:
D = [
    [2.1756, 4.0231, -2.1732, 5.1967, 17.102],
    [-4.0231, 6, 0, 1.1973, -6.1593], 
    [-1, -5.2107, 1.1111, 0, 3.0004],
    [6.0235, 7, 0, -4.1561, 0]
]

sol = eliminacion_gaussiana(D)
print(sol)

[2.9398512  0.0706777  5.67773512 4.37981223]
